In [1]:
import numpy as  np
import scipy.optimize as opt

# Definir la función cos(xe^x)
def f(x):
    return np.cos(x * np.exp(x))

# Intervalos iniciales de búsqueda
# Vamos a generar varios intervalos donde buscar los ceros.
# Sabemos que cos(x) oscila, por lo que podemos usar una búsqueda lineal amplia.
intervalos = np.linspace(0, 10, 1000)  # Generar un rango amplio de valores para buscar ceros.

# Lista para almacenar los ceros
ceros = [0.]

# Buscar los ceros usando el método de bisección entre intervalos consecutivos
for i in range(len(intervalos) - 1):
    try:
        cero = opt.brentq(f, intervalos[i], intervalos[i+1])  # Encontrar cero en el intervalo
        if not any(np.isclose(cero, c) for c in ceros):  # Evitar duplicados
            ceros.append(cero)
    except ValueError:
        # Si no hay cambio de signo en el intervalo, no se encuentra ningún cero
        pass

# Imprimir los primeros 30 ceros encontrados
print(ceros[:31])

[0.0, 0.7454072589480277, 1.2931296378793684, 1.5944756694307232, 1.8062435515489421, 1.9705132439062034, 2.1051101734106443, 2.2193277348614515, 2.3186484535808582, 2.40658663840291, 2.4855341131377173, 2.5571944165337674, 2.6228249566041004, 2.6833809734658964, 2.7396056020953834, 2.792088612778438, 2.8413060770363625, 2.887647953063894, 2.9314377607706947, 2.9729469260586763, 3.0124054417317625, 3.050009926718075, 3.085929811475762, 3.1203121501256628, 3.1532854102989094, 3.18496249116088, 3.2154431511936337, 3.2448159792938838, 3.273160008718829, 3.300546048958694, 3.3270377928003456]


In [2]:
ceros = np.array(ceros[:31])
ceros

array([0.        , 0.74540726, 1.29312964, 1.59447567, 1.80624355,
       1.97051324, 2.10511017, 2.21932773, 2.31864845, 2.40658664,
       2.48553411, 2.55719442, 2.62282496, 2.68338097, 2.7396056 ,
       2.79208861, 2.84130608, 2.88764795, 2.93143776, 2.97294693,
       3.01240544, 3.05000993, 3.08592981, 3.12031215, 3.15328541,
       3.18496249, 3.21544315, 3.24481598, 3.27316001, 3.30054605,
       3.32703779])

In [3]:
def cuadratura_adaptativa(f, a, b, tol):
    # Calcula la integral en el intervalo [a, b] con dos métodos
    def integrar(f, a, b):
        # Regla de Simpson
        c = (a + b) / 2.0
        return (b - a) / 6.0 * (f(a) + 4.0 * f(c) + f(b))
    
    # Método recursivo para la cuadratura adaptativa
    def adaptativa(f, a, b, tol, integral_previa):
        c = (a + b) / 2.0
        integral_izquierda = integrar(f, a, c)
        integral_derecha = integrar(f, c, b)
        integral_actual = integral_izquierda + integral_derecha
        
        # Estimación del error
        error = abs(integral_actual - integral_previa) / 15.0

        #print(error)
        
        if error < tol:
            return integral_actual
        else:
            # Refinar dividiendo el intervalo en dos
            izquierda = adaptativa(f, a, c, tol / 2.0, integral_izquierda)
            derecha = adaptativa(f, c, b, tol / 2.0, integral_derecha)
            return izquierda + derecha
    
    # Calcular la integral inicial
    integral_inicial = integrar(f, a, b)
    
    # Llamar a la función recursiva
    return adaptativa(f, a, b, tol, integral_inicial)

# Ejemplo de uso
f = lambda x: np.cos( x*np.exp(x) )  # Función a integrar
resultado = cuadratura_adaptativa(f, 0, 0.7454072589, 1e-8)
print("Resultado de la integración:", resultado)

Resultado de la integración: 0.5494499247042615


In [4]:
resultado2 = cuadratura_adaptativa(f, 0.7454072589,1.293129638, 1e-10)
resultado2

-0.3400724368068573

In [5]:
resultado3 = cuadratura_adaptativa(f,1.293129638,1.594475669, 1e-10)
resultado3

0.19055587941252333

In [6]:
Sn = np.array([])
suma_ = 0.

for i in range(len(ceros)-1):
    suma_ += cuadratura_adaptativa(f, ceros[i], ceros[i+1], 1e-13)
    Sn = np.append(Sn, suma_)

In [7]:
Sn

array([0.54944992, 0.20937749, 0.39993337, 0.26553955, 0.36992721,
       0.2843417 , 0.35699409, 0.29380384, 0.34976014, 0.29951984,
       0.34512598, 0.30335511, 0.34189783, 0.30611082, 0.33951713,
       0.30818876, 0.33768723, 0.30981286, 0.3362358 , 0.31111797,
       0.33505579, 0.31219016, 0.33407717, 0.31308703, 0.33325215,
       0.31384857, 0.33254699, 0.31450343, 0.3319372 , 0.31507269])

In [8]:
# Haciendo el promedio hasta 20, para mejorar la precision
Sm = np.zeros((Sn.shape[0],20))
Sm[:,0] = Sn
Sm

array([[0.54944992, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.20937749, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.39993337, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.26553955, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0

In [9]:
for j in range(1,Sm.shape[1]):
    for i in range(Sm.shape[0]-j):
        Sm[i,j] = 0.5*(Sm[i+1,j-1]+Sm[i,j-1])

In [10]:
Sm[:,-1]

array([0.32336745, 0.32336743, 0.32336743, 0.32336743, 0.32336743,
       0.32336743, 0.32336743, 0.32336743, 0.32336743, 0.32336743,
       0.32336743, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ])

In [14]:
Sm[10,-1]

0.3233674316777767