<a href="https://colab.research.google.com/github/asegura4488/MetodosComputacionalesI2025/blob/main/Semana8/EliminacionGaussiana.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
A = np.array([[3,-1,-1],[-1.,3.,1.],[2,1,4]])
b = np.array([1.,3.,7.])

In [3]:
np.linalg.solve(A,b)

array([1., 1., 1.])

In [ ]:
# Necesitamos llevar el sistema de ecuaciones a una triangular superior
# Los pivotes deben diferentes de 0: a través de intercambio de feliz

In [5]:
def TriangularSuperior(A,b=None):

  A = np.array(A, dtype=float, copy=True)
  n = A.shape[0]
  y = None if b is None else np.array(b, dtype=float, copy=True)

  for k in range(n):

    if A[k,k] == 0:
      raise ValueError("Error pivote")
    else:
      pivote = A[k,k]

      for i in range(k+1,n):
        #
        print(A[i,k])

  return (A,y) if b is not None else A

In [6]:
TriangularSuperior(A)

-1.0
2.0
1.0


array([[ 3., -1., -1.],
       [-1.,  3.,  1.],
       [ 2.,  1.,  4.]])

In [ ]:
A

array([[ 3., -1., -1.],
       [-1.,  3.,  1.],
       [ 2.,  1.,  4.]])

In [ ]:
for i in reversed(range(10)):
  print(i)

9
8
7
6
5
4
3
2
1
0
