<a href="https://colab.research.google.com/github/asegura4488/MetodosComputacionalesI2025/blob/main/Semana8/EliminacionGaussiana.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np
import matplotlib.pyplot as plt

In [9]:
A = np.array([[3,-1,-1],[-1.,3.,1.],[2,1,4]])
b = np.array([1.,3.,7.])

In [10]:
np.linalg.solve(A,b)

array([1., 1., 1.])

In [4]:
# Necesitamos llevar el sistema de ecuaciones a una triangular superior
# Los pivotes deben diferentes de 0: a través de intercambio de feliz

In [22]:
def TriangularSuperior(A,b=None):

  A = np.array(A, dtype=float, copy=True)
  n = A.shape[0]
  y = None if b is None else np.array(b, dtype=float, copy=True)

  for k in range(n):

    if A[k,k] == 0:
      raise ValueError("Error pivote")
    else:
      pivote = A[k,k]
      #print(pivote)
      for i in range(k+1,n):
        # Factor de elminacion
        m_ik = A[i,k] / pivote
        A[i, k:] = A[i, k:] - m_ik * A[k, k:]
        if y is not None:
          y[i] = y[i] - m_ik * y[k]


  return (A,y) if b is not None else A

In [23]:
U,y = TriangularSuperior(A,b)

In [24]:
U

array([[ 3.        , -1.        , -1.        ],
       [ 0.        ,  2.66666667,  0.66666667],
       [ 0.        ,  0.        ,  4.25      ]])

In [25]:
y

array([1.        , 3.33333333, 4.25      ])