<a href="https://colab.research.google.com/github/asegura4488/MetodosComputacionalesI2025/blob/main/Semana8/EliminacionGaussiana.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
A = np.array([[3,-1,-1],[-1.,3.,1.],[2,1,4]])
b = np.array([1.,3.,7.])

In [4]:
np.linalg.solve(A,b)

array([1., 1., 1.])

In [5]:
# Necesitamos llevar el sistema de ecuaciones a una triangular superior
# Los pivotes deben diferentes de 0: a través de intercambio de feliz

In [31]:
def TriangularSuperior(A_):

  A = A_.copy()
  n = A.shape[0]

  for i in range(n): # Iteramos sobre cada fila
    print(A[i,:])
    for j in range(i+1,n):
      #print(A[i,:],i,A[j,:],j)
      #print(A[j,i]) # En donde estoy??????????
      a = A[j,i]/A[i,i]
      #print(a*A[i,:],'aca')
      A[j,:] -= a*A[i,:]
      #print(A[j,:])

  print(A)

In [32]:
TriangularSuperior(A)

[ 3. -1. -1.]
[0.         2.66666667 0.66666667]
[0.   0.   4.25]
[[ 3.         -1.         -1.        ]
 [ 0.          2.66666667  0.66666667]
 [ 0.          0.          4.25      ]]


In [12]:
A

array([[ 3., -1., -1.],
       [-1.,  3.,  1.],
       [ 2.,  1.,  4.]])

In [33]:
for i in reversed(range(10)):
  print(i)

9
8
7
6
5
4
3
2
1
0
